#!/bin/bash
#
# generate-inventory.sh
# Generates Ansible inventory from Terraform outputs
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANSIBLE_DIR="$(dirname "$SCRIPT_DIR")"
TERRAFORM_DIR="$(dirname "$ANSIBLE_DIR")/terraform"
INVENTORY_FILE="$ANSIBLE_DIR/inventory/hosts.local.yml"

echo "==> Generating Ansible inventory from Terraform outputs..."

# Check if terraform directory exists
if [ ! -d "$TERRAFORM_DIR" ]; then
    echo "Error: Terraform directory not found at $TERRAFORM_DIR"
    exit 1
fi

# Change to terraform directory and get outputs
cd "$TERRAFORM_DIR"

# Check if Terraform is initialized
if [ ! -d ".terraform" ]; then
    echo "Error: Terraform not initialized. Run 'terraform init' first."
    exit 1
fi

# Get Terraform outputs as JSON
echo "==> Fetching Terraform outputs..."
TF_OUTPUT=$(terraform output -json 2>/dev/null || true)

if [ -z "$TF_OUTPUT" ] || [ "$TF_OUTPUT" = "{}" ]; then
    echo "Error: No Terraform outputs found. Has infrastructure been deployed?"
    exit 1
fi

# Extract server details
SERVER_DETAILS=$(echo "$TF_OUTPUT" | jq -r '.server_details.value // empty')

if [ -z "$SERVER_DETAILS" ] || [ "$SERVER_DETAILS" = "null" ]; then
    echo "Error: No server_details output found in Terraform state"
    exit 1
fi

# Start building inventory YAML
echo "==> Building inventory..."
cat > "$INVENTORY_FILE" << 'EOF'
---
# Generated by scripts/generate-inventory.sh
# DO NOT EDIT MANUALLY - This file is automatically generated from Terraform outputs

all:
  children:
    session_nodes:
      hosts:
EOF

# Parse server details and add each host
echo "$SERVER_DETAILS" | jq -r 'to_entries[] | "\(.key):\(.value.ip)"' | while IFS=: read -r hostname ip; do
    echo "        $hostname:" >> "$INVENTORY_FILE"
    echo "          ansible_host: $ip" >> "$INVENTORY_FILE"
    echo "          node_public_ip: $ip" >> "$INVENTORY_FILE"
done

# Validate the generated inventory
if [ ! -s "$INVENTORY_FILE" ]; then
    echo "Error: Generated inventory is empty"
    exit 1
fi

echo "==> Inventory generated successfully at: $INVENTORY_FILE"
echo ""
echo "Contents:"
cat "$INVENTORY_FILE"
echo ""
echo "==> Verifying inventory..."
cd "$ANSIBLE_DIR"
if ansible-inventory --list -i "$INVENTORY_FILE" > /dev/null 2>&1; then
    echo "✓ Inventory validation passed"
else
    echo "✗ Inventory validation failed"
    exit 1
fi

echo ""
echo "==> Next steps:"
echo "  1. Review the inventory: cat $INVENTORY_FILE"
echo "  2. Test connectivity: ansible session_nodes -m ping"
echo "  3. Run playbook: ansible-playbook playbooks/site.yml -e \"l2_provider_url=\$(op read 'op://Private/DRPC/API URL')\""
